version: '3.7'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
    - type: bind
      source: ./nginx.conf
      target: /etc/nginx/nginx.conf
    ports:
    - target: 80
      published: 80
      protocol: tcp
    depends_on:
    - front_end

  front_end:
    build: ./front_end
    container_name: front_end
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    depends_on:
    - service_4

  service_2:
    build: ./service_2
    container_name: service_2
    ports:
    - target: 5002
      published: 5002
      protocol: tcp

  service_3:
    build: ./service_3
    container_name: service_3
    ports:
    - target: 5003
      published: 5003
      protocol: tcp

  service_4:
    build: ./service_4
    container_name: service_4
    ports:
    - target: 5004
      published: 5004
      protocol: tcp
    depends_on:
    - service_2
    - service_3
